version: "3"
services:
  django:
    build: ./
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    command: python /django/app/manage.py runserver 0:8000
    env_file:
      - .env

  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
